version: '3'
services:
  distdb:
    build:
      context: ./
      dockerfile: dist.DockerFile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: dbname
    # command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    volumes:
      - /Users/kathan/Documents/dbdata:/var/lib/mysql